Docker Compose Guide Update
spring-guides/gs-messaging-redis pull request #31
Opened 2024-06-20 16:18 UTC by robertmcnees

This PR rewrites a large portion of the guide to use Spring Boot Docker Compose Support. The pattern is similar to updates previously merged in [MySQL](https://github.com/spring-guides/gs-accessing-data-mysql/pull/61).

Instructions on using Homebrew were removed in favor of a preference to use Spring Boot Docker compose support. This should allow for an easier getting started experience and not be specific to Mac users.

Additionally to adding Docker Compose, a section was added to run the application as a jar file and a Docker container. The Native section of the common file was excluded because this guide will require a custom hint to compile natively.

Also addresses issues #29 and #30.

2024-06-21 09:45 UTC, mp911de commented on README.adoc
> +To run the code without Spring Boot Docker Compose support, you need a version of RabbitMQ running locally to connect to.
Nit: Redis instead of RabbitMQ

2024-06-25 13:08 UTC, Buzzardo requested changes

2024-06-25 13:08 UTC, Buzzardo commented on README.adoc
> +You will also need to add configuration to an `application.properties` file, as described in greater detail in the <<_preparing_to_build_the_application>> section.
Remove `will`.

2024-06-25 13:08 UTC, Buzzardo commented on README.adoc
> +The `./gradlew bootRun` and `./mvnw spring-boot:run` commands will launch the application and automatically find the compose.yaml file.
Remove `will`.

2024-06-25 13:08 UTC, Buzzardo commented on README.adoc
> +To run the code without Spring Boot Docker Compose support, you need a version of Redis running locally to connect to.
I would change `to connect to.` to `to which to connect.` Better still would be to drop all three words.

2024-06-26 09:39 UTC, merged